#!/usr/bin/env bash
# In-container build script for Lean's linux_wasm32 target.
#
# Mounts assumed:
#   /work/lean4    -> vendor/lean4-src on host (Lean source)
#   /work/build    -> build-wasm/ on host     (CMake build dir, persisted)
#   /cache/ccache  -> ccache cache            (persisted across runs)
#
# Env knobs:
#   LEAN_MULTI_THREAD=OFF   -> disable Lean's threading (safer in browser)
#   PROXY_TO_PTHREAD=1      -> link with -s PROXY_TO_PTHREAD (alt fix)
#   JOBS=N                  -> parallel make jobs (default: nproc)
#
# Phase: stage0 (native 32-bit) → stage1 (WASM via emsdk)

set -euo pipefail

# Bind-mounted volumes have host uid/gid which git refuses to operate on
# unless we whitelist them. ExternalProject_Add uses git for cadical etc.
git config --global --add safe.directory '*'

LEAN_SRC=/work/lean4
BUILD_DIR=/work/build
JOBS=${JOBS:-$(nproc)}
LEAN_MULTI_THREAD=${LEAN_MULTI_THREAD:-OFF}
PROXY_TO_PTHREAD=${PROXY_TO_PTHREAD:-0}

# emcc spawns Node tools (acorn-optimizer, wasm-opt's JS minifier) that
# default to a 2GB heap. Lean's lean.js is ~120MB minified; minifying it
# blows past the default heap. Bump to 8GB.
export NODE_OPTIONS="--max-old-space-size=8192"

if [ ! -d "$LEAN_SRC/src" ]; then
  echo "[build] no Lean source at $LEAN_SRC; mount it from host" >&2
  exit 2
fi

# CMake options from PR #2599 (Web Assembly Build), with our threading toggle.
CMAKE_OPTS=(
  -DCMAKE_C_COMPILER_WORKS=1
  -DSTAGE0_USE_GMP=OFF
  -DSTAGE0_LEAN_EXTRA_CXX_FLAGS='-m32'
  -DSTAGE0_LEANC_OPTS='-m32'
  -DSTAGE0_CMAKE_CXX_COMPILER=clang++
  -DSTAGE0_CMAKE_C_COMPILER=clang
  -DSTAGE0_CMAKE_EXECUTABLE_SUFFIX=""
  -DUSE_GMP=OFF
  -DMMAP=OFF
  -DSTAGE0_MMAP=OFF
  # The CMake option in src/CMakeLists.txt is named MULTI_THREAD (line 56),
  # NOT LEAN_MULTI_THREAD. Passing the wrong name leaves it at the default
  # ON, silently producing a pthread/-matomics build that creates Workers at
  # runtime. Pass both for safety: MULTI_THREAD is the real one; the
  # LEAN_-prefixed variant is for the env var below and matches log output.
  -DMULTI_THREAD="$LEAN_MULTI_THREAD"
  -DLEAN_MULTI_THREAD="$LEAN_MULTI_THREAD"
  -DCMAKE_AR=$EMSDK/upstream/emscripten/emar
  -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
  -DCMAKE_BUILD_TYPE=Release
  # Skip mimalloc's test executable — it fails to link under Emscripten
  # due to emmalloc_free symbol resolution. We only need the library.
  -DMI_BUILD_TESTS=OFF
  -DMI_BUILD_OBJECT=OFF
  -DMI_BUILD_SHARED=OFF
  -DBUILD_TESTING=OFF
  # Force the system default linker (GNU ld). Lean's CMake auto-appends
  # -fuse-ld=lld when lld is found, but Ubuntu clang-14 + lld-14 + GCC-11
  # multilib disagrees on default emulation under -m32 (lld targets elf64,
  # objects are elf32). GNU ld handles -m32 multilib without issue.
  -DLEAN_EXTRA_LINKER_FLAGS=
)

if [ "$PROXY_TO_PTHREAD" = "1" ]; then
  # Append to whatever EMSCRIPTEN_SETTINGS the CMake injects.
  CMAKE_OPTS+=( -DLEAN_EXTRA_LINKER_FLAGS="-sPROXY_TO_PTHREAD=1 -sPTHREAD_POOL_SIZE=4" )
fi

echo "[build] Lean source:      $LEAN_SRC"
echo "[build] Build dir:        $BUILD_DIR"
echo "[build] Jobs:             $JOBS"
echo "[build] LEAN_MULTI_THREAD: $LEAN_MULTI_THREAD"
echo "[build] PROXY_TO_PTHREAD:  $PROXY_TO_PTHREAD"
echo "[build] emcc version:     $(emcc --version | head -1)"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Check for Makefile, not just CMakeCache.txt — a failed configure leaves a
# stale cache but no Makefile, which would confuse `make`.
if [ ! -f Makefile ]; then
  # Invoke the ROOT CMakeLists.txt (the stage coordinator). It orchestrates
  # stage0 (native 32-bit) → stage1 (WASM) via ExternalProject. The src/
  # CMakeLists rejects being invoked directly with "STAGE must be set".
  # emsdk 3.x also requires `emcmake cmake` (not `emconfigure cmake`).
  echo "[build] running emcmake cmake from ROOT of Lean source..."
  emcmake cmake "${CMAKE_OPTS[@]}" "$LEAN_SRC"
else
  echo "[build] reusing existing CMake cache"
fi

# Build with progressive resilience: if the stage0 stdlib.make leanir
# rule lacks -m32 (a Lean-side generator quirk for our config), patch it
# and continue. The stdlib.make is regenerated by the make_stdlib target,
# so we keep retrying until the patch has been applied to the final form.
echo "[build] make -j$JOBS..."
patch_leanir_m32() {
  local mk=/work/build/stage0/stdlib.make
  if [ -f "$mk" ] && grep -qE '^\s*"/work/build/stage0/leanc.sh" \$<  -lstdc++.*-lleanshared  -o \$@$' "$mk"; then
    echo "[build] patching stdlib.make leanir rule (adding -m32)..."
    sed -i 's|"/work/build/stage0/leanc.sh" \$<  -lstdc++ -Wl,-rpath=\\\$\$ORIGIN/../lib:\\\$\$ORIGIN/../lib/lean -rdynamic -lInit_shared -lleanshared_2 -lleanshared_1 -lleanshared  -o \$@|"/work/build/stage0/leanc.sh" \$< -lstdc++ -Wl,-rpath=\\\$\$ORIGIN/../lib:\\\$\$ORIGIN/../lib/lean -rdynamic -lInit_shared -lleanshared_2 -lleanshared_1 -lleanshared -m32 -I/work/build/stage0/include -O3 -DNDEBUG -o \$@|' "$mk"
  fi
}

set +e
attempt=0
while [ $attempt -lt 3 ]; do
  attempt=$((attempt + 1))
  echo "[build] attempt $attempt"
  time make -j"$JOBS"
  rc=$?
  if [ $rc -eq 0 ]; then break; fi
  patch_leanir_m32
done
set -e
[ $rc -eq 0 ] || { echo "[build] make failed after $attempt attempts (rc=$rc)" >&2; exit $rc; }

echo "[build] artifacts in $BUILD_DIR/shell/ (lean.js, lean.wasm, lean.worker.js)"
ls -lh "$BUILD_DIR/shell/" 2>/dev/null | head -10 || true
